name: Build Docker Image

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      -
        name: Build theme
        run: |
          git clone https://github.com/dxkite/explorer-web.git
          cd explorer-web
          npm install
          npm run build
          cp -r ./dist ../static/
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      -
        name: Build
        run: |
          go build -v -o ./explore-me -ldflags="-s -w" ./cmd/explore-me
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/explore-me:latest
      -
        if: startsWith(github.ref, 'refs/tags/')
        name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
      -
        if: startsWith(github.ref, 'refs/tags/')
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/explore-me:${{ steps.tag.outputs.tag }}